/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_flash3388_flashlib_robot_hal_ANALOGJNI */

#ifndef _Included_edu_flash3388_flashlib_robot_hal_ANALOGJNI
#define _Included_edu_flash3388_flashlib_robot_hal_ANALOGJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    getGlobalSampleRate
 * Signature: (V)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_getGlobalSampleRate
  (JNIEnv *, jclass);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    getMaxAnalogPortVoltage
 * Signature: (V)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_getMaxAnalogPortVoltage
  (JNIEnv *, jclass);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    getMaxAnalogPortValue
 * Signature: (V)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_getMaxAnalogPortValue
  (JNIEnv *, jclass);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    checkAnalogInputPortValid
 * Signature: (B)I
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_checkAnalogInputPortValid
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    checkAnalogInputPortTaken
 * Signature: (B)I
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_checkAnalogInputPortTaken
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    checkAnalogOutputPortValid
 * Signature: (B)I
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_checkAnalogOutputPortValid
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    checkAnalogOutputPortTaken
 * Signature: (B)I
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_checkAnalogOutputPortTaken
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    initializeAnalogInputPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_initializeAnalogInputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    initializeAnalogOutputPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_initializeAnalogOutputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    freeAnalogInputPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_freeAnalogInputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    freeAnalogOutputPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_freeAnalogOutputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    getAnalogValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_getAnalogValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    getAnalogVoltage
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_getAnalogVoltage
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    setAnalogVoltage
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_setAnalogVoltage
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    setAnalogValue
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_setAnalogValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    enableAnalogInputAccumulator
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_enableAnalogInputAccumulator
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    resetAnalogInputAccumulator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_resetAnalogInputAccumulator
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    setAnalogInputAccumulatorCenter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_setAnalogInputAccumulatorCenter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    getAnalogInputAccumulatorValue
 * Signature: (I)L
 */
JNIEXPORT jlong JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_getAnalogInputAccumulatorValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    getAnalogInputAccumulatorCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_getAnalogInputAccumulatorCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    convertAnalogValueToVoltage
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_convertAnalogValueToVoltage
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_ANALOGJNI
 * Method:    convertAnalogVoltageToValue
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_ANALOGJNI_convertAnalogVoltageToValue
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
