/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_flash3388_flashlib_robot_hal_DIOJNI */

#ifndef _Included_edu_flash3388_flashlib_robot_hal_DIOJNI
#define _Included_edu_flash3388_flashlib_robot_hal_DIOJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    checkDigitalInputPortValid
 * Signature: (B)I
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_checkDigitalInputPortValid
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    checkDigitalInputPortTaken
 * Signature: (B)I
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_checkDigitalInputPortTaken
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    checkDigitalOutputPortValid
 * Signature: (B)I
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_checkDigitalOutputPortValid
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    checkDigitalOutputPortTaken
 * Signature: (B)I
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_checkDigitalOutputPortTaken
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    initializeDigitalInputPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_initializeDigitalInputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    initializeDigitalOutputPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_initializeDigitalOutputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    freeDigitalInputPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_freeDigitalInputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    freeDigitalOutputPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_freeDigitalOutputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    getDIO
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_getDIO
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    setDIO
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_setDIO
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_DIOJNI
 * Method:    pulseOutDIO
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_DIOJNI_pulseOutDIO
  (JNIEnv *, jclass, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
