/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_flash3388_flashlib_hal_HAL */

#ifndef _Included_edu_flash3388_flashlib_hal_HAL
#define _Included_edu_flash3388_flashlib_hal_HAL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_flash3388_flashlib_hal_HAL
 * Method:    initialize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_hal_HAL_initialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_HAL
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_hal_HAL_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     edu_flash3388_flashlib_hal_HAL
 * Method:    boardName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_flash3388_flashlib_hal_HAL_boardName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
