/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_flash3388_flashlib_robot_hal_PWMJNI */

#ifndef _Included_edu_flash3388_flashlib_robot_hal_PWMJNI
#define _Included_edu_flash3388_flashlib_robot_hal_PWMJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_flash3388_flashlib_robot_hal_PWMJNI
 * Method:    initializePWMPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_PWMJNI_initializePWMPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_PWMJNI
 * Method:    freePWMPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_PWMJNI_freePWMPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_PWMJNI
 * Method:    setPWMRaw
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_PWMJNI_setPWMRaw
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_PWMJNI
 * Method:    setPWMDuty
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_PWMJNI_setPWMDuty
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_PWMJNI
 * Method:    setPWMFrequency
 * Signature: (I)F
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_PWMJNI_setPWMFrequency
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_PWMJNI
 * Method:    getPWMRaw
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_PWMJNI_getPWMRaw
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_PWMJNI
 * Method:    getPWMDuty
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_robot_hal_PWMJNI_getPWMDuty
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_PWMJNI
 * Method:    getPWMFrequency
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_robot_hal_PWMJNI_getPWMFrequency
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
