/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_flash3388_flashlib_robot_hal_COUNTERJNI */

#ifndef _Included_edu_flash3388_flashlib_robot_hal_COUNTERJNI
#define _Included_edu_flash3388_flashlib_robot_hal_COUNTERJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_flash3388_flashlib_robot_hal_COUNTERJNI
 * Method:    initializePulseCounter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_COUNTERJNI_initializePulseCounter
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_COUNTERJNI
 * Method:    freePulseCounter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_COUNTERJNI_freePulseCounter
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_COUNTERJNI
 * Method:    resetPulseCounter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_robot_hal_COUNTERJNI_resetPulseCounter
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_COUNTERJNI
 * Method:    getPulseCounterCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_robot_hal_COUNTERJNI_getPulseCounterCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_robot_hal_COUNTERJNI
 * Method:    getPulseCounterPeriod
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_robot_hal_COUNTERJNI_getPulseCounterPeriod
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
