/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_flash3388_flashlib_hal_ANALOGJNI */

#ifndef _Included_edu_flash3388_flashlib_hal_ANALOGJNI
#define _Included_edu_flash3388_flashlib_hal_ANALOGJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     edu_flash3388_flashlib_hal_ANALOGJNI
 * Method:    initializeAnalogInput
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_hal_ANALOGJNI_initializeAnalogInput
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_ANALOGJNI
 * Method:    initializeAnalogOutput
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_hal_ANALOGJNI_initializeAnalogOutput
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_ANALOGJNI
 * Method:    freeAnalogInput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_hal_ANALOGJNI_freeAnalogInput
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_ANALOGJNI
 * Method:    freeAnalogOutput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_hal_ANALOGJNI_freeAnalogOutput
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_ANALOGJNI
 * Method:    getAnalogValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_hal_ANALOGJNI_getAnalogValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_ANALOGJNI
 * Method:    getAnalogVoltage
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_hal_ANALOGJNI_getAnalogVoltage
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_ANALOGJNI
 * Method:    setAnalogVoltage
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_hal_ANALOGJNI_setAnalogVoltage
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     edu_flash3388_flashlib_hal_ANALOGJNI
 * Method:    setAnalogValue
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_hal_ANALOGJNI_setAnalogValue
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
