/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_flash3388_flashlib_hal_PWMJNI */

#ifndef _Included_edu_flash3388_flashlib_hal_PWMJNI
#define _Included_edu_flash3388_flashlib_hal_PWMJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     edu_flash3388_flashlib_hal_PWMJNI
 * Method:    initializePwm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_hal_PWMJNI_initializePWM
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_PWMJNI
 * Method:    freePwm
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_hal_PWMJNI_freePWM
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_PWMJNI
 * Method:    setRaw
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_hal_PWMJNI_setRaw
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_PWMJNI
 * Method:    setDuty
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_edu_flash3388_flashlib_hal_PWMJNI_setDuty
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     edu_flash3388_flashlib_hal_PWMJNI
 * Method:    getRaw
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_flash3388_flashlib_hal_PWMJNI_getRaw
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_flash3388_flashlib_hal_PWMJNI
 * Method:    getDuty
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_edu_flash3388_flashlib_hal_PWMJNI_getDuty
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
